branches:
  only:
    - master
language: node_js
node_js:
  - "4"
env:
  - NG_DIR=$TRAVIS_BUILD_DIR/ng
before_script:
  - cd $NG_DIR
  - gem install compass
  - npm install grunt-cli -g
  - npm install bower -g
  - npm install
  - bower install
script:
  - cd $NG_DIR
  - grunt build
