branches:
  only:
    - master
language: node_js
node_js:
  - '0.10'
env:
  - NG_DIR=ng
before_script:
  - cd $NG_DIR
  - npm install grunt-cli -g
  - npm install bower -g
  - npm install
  - bower install
script:
  - cd $NG_DIR
  - grunt build
  - popd
